vich_uploader:
    db_driver: orm

    mappings:
        rncp:
            uri_prefix: /images/rncp
            upload_destination: '%kernel.project_dir%/public/images/rncp'
        formation:
            uri_prefix: /images/formation
            upload_destination: '%kernel.project_dir%/public/images/formation'
        carousels:
            uri_prefix: /images/carousels
            upload_destination: '%kernel.project_dir%/public/images/carousels'
        accueil:
            uri_prefix: /images/accueil
            upload_destination: '%kernel.project_dir%/public/images/accueil'
        avisClient:
            uri_prefix: /images/avisClient
            upload_destination: '%kernel.project_dir%/public/images/avisClient'
